//////////////////////////////////////////////////////////////////////
///
/// <summary>
/// Implements a RESTful API handler for managing todo items. Provides full
/// CRUD (Create, Read, Update, Delete) operations for todo items through
/// REST endpoints.
/// </summary>
///
///
/// <remarks>
/// This handler extends RestHandler to provide:
/// - Automatic parameter type handling (converts id to numeric, todoitem to object)
/// - Automatic result enveloping (wraps results in standard JSON envelope)
/// - CORS support for cross-origin requests
/// - Error handling with HTTP status codes and error messages
/// - Dictionary support for UI metadata (states, priorities)
/// <para/>
/// REST API Endpoints:
/// - GET    /todoitems          - Retrieves all todo items with dictionaries
/// - GET    /todoitems/{id}     - Retrieves a single todo item by ID
/// - POST   /todoitems          - Creates a new todo item
/// - PUT    /todoitems/{id}     - Updates an existing todo item
/// - DELETE /todoitems/{id}     - Deletes a todo item by ID
/// <para/>
/// Special case: GET /todoitems/0 returns a default empty todo item
/// template for creating new items.
/// </remarks>
///
///
/// <copyright>
/// Alaska Software Inc. (c) 2025. All rights reserved.
/// </copyright>
///
//////////////////////////////////////////////////////////////////////


CLASS TodoEditHandler FROM RestHandler
  EXPORTED:
  CLASS METHOD onRegister()

  METHOD createTodoItem()
  METHOD updateTodoItem()
  METHOD deleteTodoItem()

  METHOD getTodoItems()
  METHOD getTodoItemById()

  HIDDEN:
  METHOD validateTodoItem()
  METHOD fetchTodoItemById()
ENDCLASS

/// <summary>
/// Establishes REST interface mappings and parameter types. This method is
/// automatically called when the handler is registered with a RestEndpoint.
/// </summary>
/// <param name="oEP">The endpoint this handler is being registered with</param>
/// <returns value="self"/>
/// <remarks>
/// Configures:
/// - CORS allowed methods for cross-origin requests
/// - Parameter types for automatic type conversion
/// - URL routing to handler methods
/// <para/>
/// The ::id syntax in URLs (e.g., /todoitems/::id) creates path parameters
/// that are automatically extracted and type-converted based on :addType() mappings.
/// </remarks>
///
CLASS METHOD TodoEditHandler:onRegister(oEP)

  ::CrossOrigin:allowMethods( "GET, POST, DELETE, PUT" )

  ::addType( "todoitem", "O" )
  ::addType( "id", "N" )

  oEP:map( "GET",    "/todoitems", "/TodoEditHandler/getTodoItems" )
  oEP:map( "GET",    "/todoitems/::id", "/TodoEditHandler/getTodoItemById" )
  oEP:map( "DELETE", "/todoitems/::id", "/TodoEditHandler/deleteTodoItem" )
  oEP:map( "PUT",    "/todoitems/::id", "/TodoEditHandler/updateTodoItem" )
  oEP:map( "POST",   "/todoitems", "/TodoEditHandler/createTodoItem" )

RETURN SELF


/// <summary>
/// Creates a new todo item in the database.
/// </summary>
/// <param name="oTodoItem">Todo item data object from request body (JSON)</param>
/// <returns value="oCreatedTodoItem">The created todo item with assigned ID</returns>
/// <remarks>
/// REST: POST /todoitems
/// <para/>
/// Request body should contain a JSON object with todo item properties:
/// created, text, changed, state, priority. The id field is ignored as it's
/// auto-generated by the database.
/// <para/>
/// Returns HTTP 400 if validation fails.
/// </remarks>
///
METHOD TodoEditHandler:createTodoItem(oTodoItem)
   LOCAL oTDM
   LOCAL oCreatedTodoItem

   IF .NOT. ::validateTodoItem(oTodoItem)
     ::setError(400, "Invalid todo item. Validation failed.")
     RETURN
   ENDIF

   oTDM := TodoDataManager():open()
   oCreatedTodoItem := oTDM:add(oTodoItem)
   oTDM:close()

RETURN oCreatedTodoItem


/// <summary>
/// Updates an existing todo item in the database.
/// </summary>
/// <param name="nId">ID of the todo item to update (from URL path)</param>
/// <param name="oTodoItem">Updated todo item data object from request body (JSON)</param>
/// <returns value="oUpdatedTodoItem">The updated todo item</returns>
/// <remarks>
/// REST: PUT /todoitems/{id}
/// <para/>
/// The id in the URL path is used to locate the item. The id field in the
/// request body is ignored to allow copy operations between todo items.
/// <para/>
/// Returns HTTP 400 if validation fails or ID is invalid.
/// Returns HTTP 404 if the todo item is not found.
/// </remarks>
///
METHOD TodoEditHandler:updateTodoItem(nId, oTodoItem)
   LOCAL oTDM
   LOCAL oUpdatedTodoItem

   IF !::validateTodoItem(oTodoItem) .OR. nId == 0
     ::setError(400, "Invalid ID or invalid todo item. Validation failed.")
     RETURN
   ENDIF

   oTDM := TodoDataManager():open()
   oUpdatedTodoItem := oTDM:updateById(nId, oTodoItem)
   oTDM:close()

   IF IsNull(oUpdatedTodoItem)
     ::setError(404, "Requested todo item not found")
     RETURN
   ENDIF

RETURN oUpdatedTodoItem


/// <summary>
/// Deletes a todo item from the database.
/// </summary>
/// <param name="nId">ID of the todo item to delete (from URL path)</param>
/// <returns value="oData">The deleted todo item data</returns>
/// <remarks>
/// REST: DELETE /todoitems/{id}
/// <para/>
/// Returns the deleted item's data so the client can confirm which item
/// was removed.
/// <para/>
/// Returns HTTP 400 if ID is invalid.
/// Returns HTTP 404 if the todo item is not found.
/// </remarks>
///
METHOD TodoEditHandler:deleteTodoItem(nId)
   LOCAL oTDM
   LOCAL oData

   IF nId == 0
     ::setError(400, "Invalid ID in the passed parameter")
     RETURN
   ENDIF

   oTDM  := TodoDataManager():open()
   oData := oTDM:deleteById( nId )
   oTDM:close()
   IF IsNull(oData)
     ::setError(404, "Requested todo item not found")
     RETURN
   ENDIF
RETURN oData


/// <summary>
/// Retrieves all todo items from the database.
/// </summary>
/// <returns value="oResult">Object containing data array and dictionaries</returns>
/// <remarks>
/// REST: GET /todoitems
/// <para/>
/// Returns all non-deleted todo items along with dictionaries for states
/// and priorities. The dictionaries provide metadata for UI components
/// (dropdowns, selection lists, etc.).
/// <para/>
/// Response structure:
/// {
///   data: [ array of todo items ],
///   dictionaries: {
///     states: [ {id, name} ],
///     priorities: [ {id, name} ]
///   }
/// }
/// </remarks>
///
METHOD TodoEditHandler:getTodoItems()
   LOCAL aData
   LOCAL oTDM

   oTDM  := TodoDataManager():open()
   aData := oTDM:getAll()
   oTDM:close()

   // extend result with dictionary for editing
   ::addDictionary( "states" ,   TodoItemStates():getAll() )
   ::addDictionary( "priorities",TodoItemPriorities():getAll() )
RETURN aData


/// <summary>
/// Retrieves a single todo item by ID. Includes dictionaries for UI editing support.
/// </summary>
/// <param name="nId">ID of the todo item (from URL path). Special case: id=0 returns
/// an empty template for creating new items.</param>
/// <returns value="oResult">Object containing the todo item and dictionaries</returns>
/// <remarks>
/// REST: GET /todoitems/{id}
/// <para/>
/// Special behavior:
/// - id=0: Returns a default/empty todo item template with current timestamp
/// - id>0: Returns the existing todo item, or HTTP 404 if not found
/// <para/>
/// Response includes state and priority dictionaries for UI components.
/// <para/>
/// Response structure:
/// {
///   data: { todo item object },
///   dictionaries: {
///     states: [ {id, name} ],
///     priorities: [ {id, name} ]
///   }
/// }
/// </remarks>
///
METHOD TodoEditHandler:getTodoItemById(nId)
   LOCAL oTodoItem
   LOCAL oResult
   LOCAL oTDM

   IF nId == 0
     oTDM  := TodoDataManager():open()
     oTodoItem := oTDM:getDefault()
     oTDM:close()
   ELSE
     oTodoItem := ::fetchTodoItemById(nId)
     IF IsNull(oTodoItem)
       ::setError(404, "Requested todo item not found")
       RETURN
     ENDIF
   ENDIF

   ::addDictionary( "states" ,   TodoItemStates():getAll() )
   ::addDictionary( "priorities",TodoItemPriorities():getAll() )
RETURN oTodoItem


/// <summary>
/// Validates a todo item data object before database operations.
/// </summary>
/// <param name="oTodoItem">Todo item data object to validate</param>
/// <returns value="lValid">.T. if valid, .F. if validation fails</returns>
/// <remarks>
/// Validates that:
/// - Object has exactly 6 properties (id, created, text, changed, state, priority)
/// - created field is not empty
/// - text field is not empty
/// </remarks>
///
METHOD TodoEditHandler:validateTodoItem(oTodoItem)
   IF Len(oTodoItem) != 6 .OR. Empty(oTodoItem:created) .OR. Empty(oTodoItem:text)
     RETURN .F.
   ENDIF
RETURN .T.


/// <summary>
/// Helper method to fetch a todo item by ID from the database.
/// </summary>
/// <param name="nId">ID of the todo item to fetch</param>
/// <returns value="oTodoItem">Todo item data object, or NIL if not found</returns>
/// <remarks>
/// Internal helper that encapsulates the data access logic for retrieving
/// a single todo item. Does not perform validation or error handling.
/// </remarks>
///
METHOD TodoEditHandler:fetchTodoItemById(nId)
   LOCAL oTodoItem
   LOCAL oTDM

   oTDM := TodoDataManager():open()
   oTodoItem := oTDM:getById(nId)
   oTDM:close()
RETURN oTodoItem



